Repository Final-challenge-organization/Final-challenge, pull requests merged in 2023-10, with the labels that each got.

#10 Test/branch para teste do servidor
  Mythos/Mythos.xcodeproj/project.pbxproj
  Mythos/Mythos/Assets.xcassets/emptyCard.imageset/Ação.png
  Mythos/Mythos/Assets.xcassets/emptyCard.imageset/Contents.json
  Mythos/Mythos/Assets.xcassets/shield.imageset/Contents.json
  Mythos/Mythos/Assets.xcassets/shield.imageset/escudo 2.png
  Mythos/Mythos/Model/Card.swift
  Mythos/Mythos/Model/DataWrapper.swift
  Mythos/Mythos/Model/PlayerClient.swift
  Mythos/Mythos/Model/WebSocket.swift
  Mythos/Mythos/View/CardRepresentable.swift
  Mythos/Mythos/View/ClientSideView.swift
  Mythos/Mythos/View/ContentView.swift
  Mythos/Mythos/View/GameView.swift
  Mythos/Mythos/View/MaybeGameView.swift
  Mythos/Mythos/View/MythosApp.swift
  Mythos/Mythos/View/ParallaxView.swift
  Mythos/Mythos/View/PopUpCard.swift
  Mythos/build1
  Mythos/build4
  Mythos/terminate4
Labels: documentation, enhancement

#13 Hotfix/branch teste
  Mythos/Mythos.xcodeproj/project.pbxproj
  Mythos/Mythos/Assets.xcassets/cards/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/actionCard.imageset/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/actionCard.imageset/actionCard.png
  Mythos/Mythos/Assets.xcassets/cards/reactionCard.imageset/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/reactionCard.imageset/reactionCard.png
  Mythos/Mythos/Assets.xcassets/emptyCard.imageset/Ação.png
  Mythos/Mythos/Info.plist
  Mythos/Mythos/Model/DataWrapper.swift
  Mythos/Mythos/Model/WebSocket.swift
  Mythos/Mythos/ProjectFonts/Convergence-Regular.ttf
  Mythos/Mythos/ProjectFonts/Fonts.swift
  Mythos/Mythos/View/CardRepresentable.swift
  Mythos/Mythos/View/CardView/CardRepresentable.swift
  Mythos/Mythos/View/ContentView.swift
  Mythos/Mythos/View/MaybeGameView.swift
  Mythos/Mythos/View/WaitingRoomView/WaitingRoomView.swift
Labels: bug

#26 hotfix de novas cartas
  Mythos/Mythos.xcodeproj/project.pbxproj
  Mythos/Mythos/Model/Card.swift
  Mythos/Mythos/Model/DeckMock.swift
  Mythos/Mythos/View/CardView/CardRepresentable.swift
  Mythos/Mythos/View/MaybeGameView.swift
  Mythos/Mythos/View/PersonasView.swift
  Mythos/Mythos/View/PopUpCard.swift
Labels: bug

#28 ajustado para appstore
  Mythos/Mythos.xcodeproj/project.pbxproj
  Mythos/Mythos/Assets.xcassets/AppIcon.appiconset/Contents.json
  Mythos/Mythos/Assets.xcassets/AppIcon.appiconset/logoMythos-2.png
  Mythos/Mythos/View/HomeView/HomeView.swift
Labels: enhancement

#35 Feature/new cards
  Mythos/Mythos.xcodeproj/project.pbxproj
  Mythos/Mythos/Assets.xcassets/Colors/Contents.json
  Mythos/Mythos/Assets.xcassets/Colors/cardDescriptionColor.colorset/Contents.json
  Mythos/Mythos/Assets.xcassets/Colors/cardTitleColor.colorset/Contents.json
  Mythos/Mythos/Assets.xcassets/athena.imageset/athena 2.png
  Mythos/Mythos/Assets.xcassets/cards/actionCard.imageset/actionCard.png
  Mythos/Mythos/Assets.xcassets/cards/backCards/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/backCards/cardBack.imageset/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/backCards/cardBack.imageset/verso_carta.png
  Mythos/Mythos/Assets.xcassets/cards/cardItens/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/cardItens/escudoDeJustica.imageset/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/cardItens/escudoDeJustica.imageset/escudoDeJustica.png
  Mythos/Mythos/Assets.xcassets/cards/cardItens/flechaEncantada.imageset/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/cardItens/flechaEncantada.imageset/flechaEncantada.png
  Mythos/Mythos/Assets.xcassets/cards/cardItens/leiteMedicinal.imageset/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/cardItens/leiteMedicinal.imageset/leiteMedicinal.png
  Mythos/Mythos/Assets.xcassets/cards/cardItens/manipulacaoDeFluxo.imageset/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/cardItens/manipulacaoDeFluxo.imageset/manipulacaoDeFluxo.png
  Mythos/Mythos/Assets.xcassets/cards/cardItens/marteladaDeHefestos.imageset/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/cardItens/marteladaDeHefestos.imageset/marteladaDeHefestos.png
  Mythos/Mythos/Assets.xcassets/cards/cardItens/olharDeCiclope.imageset/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/cardItens/olharDeCiclope.imageset/olharDeCiclope.png
  Mythos/Mythos/Assets.xcassets/cards/cardItens/sandaliasAladas.imageset/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/cardItens/sandaliasAladas.imageset/sandaliasAladas.png
  Mythos/Mythos/Assets.xcassets/cards/frontCards/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/frontCards/action.imageset/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/frontCards/action.imageset/action.png
  Mythos/Mythos/Assets.xcassets/cards/frontCards/reaction.imageset/Contents.json
  Mythos/Mythos/Assets.xcassets/cards/frontCards/reaction.imageset/reaction.png
  Mythos/Mythos/Assets.xcassets/cards/reactionCard.imageset/reactionCard.png
  Mythos/Mythos/Assets.xcassets/demeter.imageset/demeter 2.jpeg
  Mythos/Mythos/Info.plist
  Mythos/Mythos/Model/Card.swift
  Mythos/Mythos/Network/WebSocket.swift
  Mythos/Mythos/ProjectFonts/Cabin-Bold.ttf
  Mythos/Mythos/ProjectFonts/Cabin-MediumItalic.ttf
  Mythos/Mythos/ProjectFonts/CaesarDressing-Regular.ttf
  Mythos/Mythos/ProjectFonts/Convergence-Regular.ttf
  Mythos/Mythos/ProjectFonts/Fonts.swift
  Mythos/Mythos/View/CardFocusedView.swift
  Mythos/Mythos/View/CardView/BackCardView.swift
  Mythos/Mythos/View/CardView/CardRepresentable.swift
  Mythos/Mythos/View/CardView/KillDeckView.swift
  Mythos/Mythos/View/MaybeGameView.swift
  Mythos/Mythos/View/MythosApp.swift
  Mythos/Mythos/View/PersonasView.swift
  Mythos/Mythos/View/PopUpCard.swift
Labels: enhancement

#36 Feature/fix animations
  Mythos/Mythos.xcodeproj/project.pbxproj
  Mythos/Mythos/Data/Model/Card.swift
  Mythos/Mythos/Data/Model/PlayerClient.swift
  Mythos/Mythos/Data/Network/DataWrapper.swift
  Mythos/Mythos/Data/Network/Protocols.swift
  Mythos/Mythos/Data/Network/WebSocket.swift
  Mythos/Mythos/Data/Network/WebSocketProtocol.swift
  Mythos/Mythos/Data/Persistence/DataStorage.swift
  Mythos/Mythos/View/ClientSideView.swift
  Mythos/Mythos/View/Configuration/ConfigurationView.swift
  Mythos/Mythos/View/Configuration/PlayerView 2.swift
  Mythos/Mythos/View/Configuration/PlayerView.swift
  Mythos/Mythos/View/GamePlay/Components/Card/BackCardView.swift
  Mythos/Mythos/View/GamePlay/Components/Card/CardFocusedView.swift
  Mythos/Mythos/View/GamePlay/Components/Card/CardRepresentable.swift
  Mythos/Mythos/View/GamePlay/Components/Card/KillDeckView.swift
  Mythos/Mythos/View/GamePlay/Components/Card/UserCardsView.swift
  Mythos/Mythos/View/GamePlay/Components/Highlights/CardHighlightsView.swift
  Mythos/Mythos/View/GamePlay/Components/Players/PersonasView.swift
  Mythos/Mythos/View/GamePlay/Components/Players/PlayerLayoutView.swift
  Mythos/Mythos/View/GamePlay/Components/SendCardButtonView.swift
  Mythos/Mythos/View/GamePlay/View/GameView.swift
  Mythos/Mythos/View/GamePlay/View/MaybeGameView.swift
  Mythos/Mythos/View/GamePlay/ViewModel/CardViewModel.swift
  Mythos/Mythos/View/Home/Components/Buttons/InventoryButtonView.swift
  Mythos/Mythos/View/Home/Components/Buttons/PlayButtonView.swift
  Mythos/Mythos/View/Home/Components/Buttons/UserButtonView.swift
  Mythos/Mythos/View/Home/HomeView.swift
  Mythos/Mythos/View/Inventory/InventoryView.swift
  Mythos/Mythos/View/MaybeGameView.swift
  Mythos/Mythos/View/MythosApp.swift
  Mythos/Mythos/View/Profile/ProfileView.swift
  Mythos/Mythos/View/Store/StoreView.swift
  Mythos/Mythos/View/WaitingRoom/ButtonConnect.swift
  Mythos/Mythos/View/WaitingRoom/ConnectedPlayersView.swift
  Mythos/Mythos/View/WaitingRoom/WaitingRoomView.swift
Labels: enhancement
